### ISSUE TITLE
error en ipv6

### ISSUE THREAD

**Issue by juanfrancisco-18** [GeiserX/genieacs-docker#15]
![image](https://github.com/GeiserX/genieacs-docker/assets/20887859/1fdee8db-f7a2-41c2-8820-81acbdc94719)
help please

**Comment by juanfrancisco-18** [comment]
my number :+573014445141 thanks

**Comment by juanfrancisco-18** [comment]
hello?

**Comment by GeiserX** [comment]
Closing as not an error related to docker

**Comment by juanfrancisco-18** [comment]
hola ok ingeniero  se que hablas en español hasta orita me di cuenta pregunta tecnica entonces donde está el error ? que tengo que hacer ? o que version tengo que instalar para que me funcione? tengo la version 1.2.9 le agradesco su respuesta gracias.

**Comment by juanfrancisco-18** [comment]
en la comunidad puse el caso y le enviado varios correos y e publicado el caso y no me han aprobado quedo atento.
