### ISSUE TITLE
instalacion no funciona

### ISSUE THREAD

**Issue by juanfrancisco-18** [GeiserX/genieacs-docker#16]
buenas tardes ingeniero se hizo la instalación con éxito pero accedo la ip al puerto 3000 pero no nos funciona nos si toca instalarle algo al debian 

quedo atento agracias.

**Comment by juanfrancisco-18** [comment]
estuve haciendo cada detalle la instalación y encontre para que los que tiene ipv6 hay que  desactivarlo porque algunos repositorios tiene problemas con ipv6.

Tambien  el comando de  donde está link de descarga ya no funciona   para instalar el docker  tocó con la pagina oficial.

+573014445141 Ingeniero Juan Francisco Suárez

**Comment by zainurihasan** [comment]
> estuve haciendo cada detalle la instalación y encontré para que los que tiene ipv6 hay que desactivarlo porque algunos repositorios tiene problemas con ipv6.
> 
> Tambien el comando de donde está link de descarga ya no funciona para instalar el Docker tocó con la pagina oficial.
> 
> +573014445141 Ingeniero Juan Francisco Suárez

can you detail it step by step how to resolve this issue?
