### ISSUE TITLE
Mongo DB issue

### ISSUE THREAD

**Issue by Shivi1771** [GeiserX/genieacs-docker#18]
When I am running the genieacs docker and the application for the api's by genieacs in the same docker environment, I tested the firmware upload api, it showed 200 status code meaning the firmware was uploaded successfully, however i checked the fs.files in mongodb compass and I didn't find the uploaded file there so where can I find the uploaded file ? Kindly please help.

**Comment by GeiserX** [comment]
Sorry, this is just my baked docker container for GenieACS, you have the [forum ](https://forum.genieacs.com/) to ask those questions. Best wishes
